# Generated by Django 3.0 on 2020-01-02 21:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_key'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='user',
            #name='address',
            #field=models.CharField(default='', max_length=255),
        #),
        #migrations.AddField(
            #model_name='user',
            #name='affiliation',
            #field=models.CharField(default='', max_length=255),
        #),
        #migrations.AddField(
            #model_name='user',
            #name='json',
            #field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        #),
        #migrations.AddField(
            #model_name='user',
            #name='phone',
            #field=models.CharField(default='', max_length=255),
        #),
        #migrations.CreateModel(
            #name='UserGroup',
            #fields=[
                #('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('created', models.DateTimeField()),
                #('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                #('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            #],
        #),
    ]
