# Generated by Django 3.0 on 2020-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(through='api.UserGroup', to='api.Group'),
        ),
    ]
